name: complete-runs

on:
  workflow_dispatch:
    inputs:
      QASE_API_TOKEN:
        description: "Qase API Token (Overrides Secret)"
        required: false
        type: string
      QASE_PROJECT_CODE:
        description: "Qase Project Code (Overrides Variable)"
        required: false
        type: string

jobs:
  run-qase-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install Dependencies
        run: go mod tidy

      - name: Set Environment Variables
        run: |
          echo "QASE_API_TOKEN=${{ github.event.inputs.QASE_API_TOKEN || secrets.QASE_API_TOKEN }}" >> $GITHUB_ENV
          echo "QASE_PROJECT_CODE=${{ github.event.inputs.QASE_PROJECT_CODE || vars.QASE_PROJECT_CODE }}" >> $GITHUB_ENV

      - name: Run Qase Script
        run: go run main.go

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qase-results
          path: |
            errors.txt
            final.txt
            results.json
            filtered.txt
          if-no-files-found: warn
